# Generated by Django 5.1.4 on 2026-05-09 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('task', '할 일'), ('meeting', '회의'), ('deadline', '마감'), ('reminder', '알림'), ('other', '기타')], default='other', max_length=20)),
                ('color', models.CharField(default='#5E6AD2', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_events',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['user', 'date'], name='personal_ev_user_id_da6c43_idx')],
            },
        ),
    ]
