# Generated by Django 5.1.4 on 2026-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', '회의'), ('trip', '출장'), ('deadline', '마감'), ('presentation', '발표'), ('milestone', '마일스톤'), ('other', '기타')], default='other', max_length=20),
        ),
    ]
