# Generated by Django 5.1.4 on 2026-05-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_workspace(apps, schema_editor):
    """기존 PersonalEvent 를 사용자의 가장 오래된 ws 로 매핑.
    멤버십이 없는 사용자(이상 케이스)의 PE 는 null 로 남아 어떤 ws 에서도 안 보임."""
    PersonalEvent = apps.get_model("me", "PersonalEvent")
    WorkspaceMember = apps.get_model("workspaces", "WorkspaceMember")

    for pe in PersonalEvent.objects.filter(workspace__isnull=True):
        first = (
            WorkspaceMember.objects
            .filter(member_id=pe.user_id)
            .order_by("created_at")
            .select_related("workspace")
            .first()
        )
        if first:
            pe.workspace_id = first.workspace_id
            pe.save(update_fields=["workspace"])


def noop_reverse(apps, schema_editor):
    """rollback 시 workspace=null 로 되돌림은 의미 없음 (FK 자체가 다음 단계에서 제거됨)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_alter_personalevent_event_type'),
        ('workspaces', '0005_user_fk_set_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_events', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='personalevent',
            index=models.Index(fields=['workspace', 'user', 'date'], name='personal_ev_workspa_54735a_idx'),
        ),
        migrations.RunPython(backfill_workspace, noop_reverse),
    ]
