# Generated by Django 5.1.4 on 2026-04-05 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('meeting', '회의'), ('trip', '출장'), ('deadline', '마감'), ('presentation', '발표'), ('milestone', '마일스톤'), ('other', '기타')], default='other', max_length=20)),
                ('color', models.CharField(default='#5E6AD2', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'db_table': 'project_events',
                'ordering': ['date'],
            },
        ),
    ]
