# Generated by Django 5.1.4 on 2026-04-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon_prop',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
