# Generated by Django 5.1.4 on 2026-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_saved_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
