# Generated by Django 5.1.4 on 2026-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='request_review_policy',
            field=models.CharField(choices=[('all', 'All members'), ('admin', 'Admin only')], default='all', max_length=10),
        ),
    ]
