# Generated by Django 5.1.4 on 2026-04-13 03:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
        ('projects', '0012_event_global_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_mentioned',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('issue_assigned', 'Issue Assigned'), ('issue_updated', 'Issue Updated'), ('comment_added', 'Comment Added'), ('issue_created', 'Issue Created')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('muted', models.BooleanField(default=False)),
                ('email_issue_assigned', models.BooleanField(blank=True, default=None, null=True)),
                ('email_issue_updated', models.BooleanField(blank=True, default=None, null=True)),
                ('email_comment_added', models.BooleanField(blank=True, default=None, null=True)),
                ('email_issue_created', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_preferences', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_notification_preferences',
                'indexes': [models.Index(fields=['project', 'email_issue_created'], name='project_not_project_b4a0df_idx')],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
