# Generated by Django 5.1.4 on 2026-04-26 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_issue_is_field'),
        ('notifications', '0003_remove_notificationpreference_email_mentioned_and_more'),
        ('workspaces', '0003_workspace_brand_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('issue_assigned', 'Issue Assigned'), ('issue_unassigned', 'Issue Unassigned'), ('issue_updated', 'Issue Updated'), ('comment_added', 'Comment Added'), ('comment_replied', 'Comment Replied'), ('issue_created', 'Issue Created'), ('mentioned', 'Mentioned')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'archived_at'], name='notificatio_recipie_805dac_idx'),
        ),
    ]
