# Generated by Django 5.1.4 on 2026-04-14 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('superuser_grant', 'Grant superuser'), ('superuser_revoke', 'Revoke superuser'), ('user_approve', 'Approve user'), ('user_suspend', 'Suspend user'), ('user_unsuspend', 'Unsuspend user'), ('user_delete', 'Delete user'), ('workspace_create', 'Create workspace'), ('workspace_delete', 'Delete workspace'), ('workspace_owner', 'Transfer workspace owner')], max_length=32)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('workspace', 'Workspace')], max_length=16)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'), models.Index(fields=['target_type', '-created_at'], name='audit_logs_target__5b42f3_idx')],
            },
        ),
    ]
