# Generated by Django 5.1.4 on 2026-03-28 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_add_priority_colors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.state'),
        ),
        migrations.AddField(
            model_name='issue',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='issueactivity',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueactivity',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects.project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issues.label'),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('project', 'sequence_id')},
        ),
    ]
