# Generated by Django 5.1.4 on 2026-03-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_soft_delete'),
        ('projects', '0002_project_archived_at_project_auto_archive_days_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['sort_order', 'sequence_id']},
        ),
        migrations.AddField(
            model_name='issue',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.module'),
        ),
    ]
