# Generated by Django 5.1.4 on 2026-03-31 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_options_issue_module'),
        ('projects', '0003_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.cycle'),
        ),
    ]
