# Generated by Django 5.1.4 on 2026-04-03 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issueattachment'),
        ('projects', '0003_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='템플릿 이름', max_length=255)),
                ('title_template', models.CharField(blank=True, default='', help_text='이슈 제목 기본값', max_length=255)),
                ('description_html', models.TextField(blank=True, default='', help_text='이슈 설명 기본값 (HTML)')),
                ('priority', models.CharField(choices=[('none', 'None'), ('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_templates', to='projects.project')),
            ],
            options={
                'db_table': 'issue_templates',
                'ordering': ['name'],
            },
        ),
    ]
