# Generated by Django 5.1.4 on 2026-04-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_font_family',
            field=models.CharField(default='pretendard', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_font_mono',
            field=models.CharField(default='jetbrains', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_font_scale',
            field=models.FloatField(default=1.0),
        ),
    ]
