# Generated by Django 5.1.4 on 2026-04-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
