# Generated by Django 5.1.4 on 2026-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_user_fk_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
