# Generated by Django 5.1.4 on 2026-04-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_doc_icon_prop'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_space_i_0bbb0c_idx',
            old_name='documents_space_parent_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_space_i_e50ed8_idx',
            old_name='documents_space_deleted_idx',
        ),
    ]
