# Generated by Django 5.1.4 on 2026-04-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_spaces_meta_and_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['sort_order', 'created_at']},
        ),
    ]
