# Generated by Django 5.1.4 on 2026-04-23 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_text', models.CharField(blank=True, default='', max_length=500)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comment_threads', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='documents.document')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comment_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_comment_threads',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.commentthread'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['thread', 'created_at'], name='document_co_thread__78c8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='commentthread',
            index=models.Index(fields=['document', 'resolved'], name='document_co_documen_5fd0aa_idx'),
        ),
    ]
