# Generated by Django 5.1.4 on 2026-04-23 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documentcomment_options_commentthread_and_more'),
        ('workspaces', '0002_workspaceinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('icon_prop', models.JSONField(blank=True, default=None, null=True)),
                ('scope', models.CharField(choices=[('built_in', 'Built-in'), ('user', 'User'), ('workspace', 'Workspace')], default='user', max_length=16)),
                ('content_html', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_templates', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'document_templates',
                'ordering': ['scope', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['scope', 'workspace'], name='document_te_scope_bda60f_idx'), models.Index(fields=['scope', 'owner'], name='document_te_scope_8993f2_idx')],
            },
        ),
    ]
