# Generated by Django 5.1.4 on 2026-04-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/covers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='document',
            name='cover_offset_y',
            field=models.IntegerField(default=50),
        ),
    ]
