# Generated by Django 5.1.4 on 2026-04-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_share_expires_at_document_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_offset_x',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='document',
            name='cover_zoom',
            field=models.FloatField(default=1.0),
        ),
    ]
