# Generated by Django 5.1.4 on 2026-04-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_cover_offset_x_document_cover_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_height',
            field=models.IntegerField(default=208),
        ),
    ]
