# Generated by Django 5.1.4 on 2026-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_cover_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preferred_width',
            field=models.CharField(choices=[('narrow', 'Narrow (860px)'), ('wide', 'Wide (full)')], default='narrow', max_length=8),
        ),
    ]
