# Generated by Django 5.1.4 on 2026-04-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_preferred_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='font_size_body',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='document',
            name='font_size_h1',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='document',
            name='font_size_h2',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='document',
            name='font_size_h3',
            field=models.IntegerField(default=22),
        ),
    ]
