# Generated by Django 5.1.4 on 2026-04-24 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_font_size_body_document_font_size_h1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_bookmarks',
                'indexes': [models.Index(fields=['user', '-created_at'], name='document_bo_user_id_e7a7e7_idx')],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
