# Generated by Django 5.1.4 on 2026-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_document_comment_author_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspace',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
