# Generated by Django 5.1.4 on 2026-04-27 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_space_privacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSpaceBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='documents.documentspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_space_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_space_bookmarks',
                'indexes': [models.Index(fields=['user', '-created_at'], name='document_sp_user_id_b2af40_idx')],
                'unique_together': {('user', 'space')},
            },
        ),
    ]
