from django.urls import path
from .views import (
    IssueListCreateView,
    IssueDetailView,
    IssueRestoreView,
    IssueTrashListView,
    IssueHardDeleteView,
    IssueArchiveListView,
    IssueArchiveView,
    IssueDuplicateView,
    SubIssueListCreateView,
    IssueCommentListCreateView,
    IssueCommentDetailView,
    IssueActivityListView,
    IssueLinkListCreateView,
    IssueLinkDetailView,
    IssueNodeLinkListCreateView,
    IssueNodeLinkDetailView,
    ProjectNodeGraphView,
    WorkspaceNodeGraphView,
    IssueAttachmentListCreateView,
    IssueAttachmentDetailView,
    LabelListCreateView,
    LabelDetailView,
    IssueTemplateListCreateView,
    IssueTemplateDetailView,
    WorkspaceMyIssuesView,
    IssueBulkUpdateView,
    IssueBulkDeleteView,
    ProjectIssueStatsView,
    WorkspaceRecentIssuesView,
    WorkspaceIssueSearchView,
    IssueDocumentLinksView,
    IssueRequestListCreateView,
    IssueRequestApproveView,
    IssueRequestRejectView,
    IssueRequestDeleteView,
)

urlpatterns = [
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/",
        IssueListCreateView.as_view(),
        name="issue-list",
    ),
    # 보관함 — 보관된 이슈 목록
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/archive/",
        IssueArchiveListView.as_view(),
        name="issue-archive-list",
    ),
    # 이슈 보관 / 보관 해제
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:pk>/archive/",
        IssueArchiveView.as_view(),
        name="issue-archive",
    ),
    # 휴지통 — 삭제된 이슈 목록 (uuid 패턴보다 먼저 배치)
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/trash/",
        IssueTrashListView.as_view(),
        name="issue-trash-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:pk>/",
        IssueDetailView.as_view(),
        name="issue-detail",
    ),
    # 이슈 딥카피 (하위 이슈 포함)
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:pk>/duplicate/",
        IssueDuplicateView.as_view(),
        name="issue-duplicate",
    ),
    # 영구 삭제
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:pk>/hard-delete/",
        IssueHardDeleteView.as_view(),
        name="issue-hard-delete",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:pk>/restore/",
        IssueRestoreView.as_view(),
        name="issue-restore",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/sub-issues/",
        SubIssueListCreateView.as_view(),
        name="sub-issue-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/comments/",
        IssueCommentListCreateView.as_view(),
        name="issue-comment-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/comments/<uuid:pk>/",
        IssueCommentDetailView.as_view(),
        name="issue-comment-detail",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/activities/",
        IssueActivityListView.as_view(),
        name="issue-activity-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/links/",
        IssueLinkListCreateView.as_view(),
        name="issue-link-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/links/<uuid:pk>/",
        IssueLinkDetailView.as_view(),
        name="issue-link-detail",
    ),
    # 이슈 간 그래프 링크(node) — 트리 경계 넘는 자유 연결. 프론트 UI 보류, 데이터/API 먼저.
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/node-links/",
        IssueNodeLinkListCreateView.as_view(),
        name="issue-node-link-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/node-links/<uuid:pk>/",
        IssueNodeLinkDetailView.as_view(),
        name="issue-node-link-detail",
    ),
    # 그래프 뷰 — 프로젝트 범위 노드 그래프 (프로젝트가 하나의 꼭지)
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/node-graph/",
        ProjectNodeGraphView.as_view(),
        name="project-node-graph",
    ),
    # 그래프 뷰 — 워크스페이스 전체 (선택적, 내부 디버그/오버뷰용)
    path(
        "workspaces/<slug:workspace_slug>/node-graph/",
        WorkspaceNodeGraphView.as_view(),
        name="workspace-node-graph",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/attachments/",
        IssueAttachmentListCreateView.as_view(),
        name="issue-attachment-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:issue_pk>/attachments/<uuid:pk>/",
        IssueAttachmentDetailView.as_view(),
        name="issue-attachment-detail",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/labels/",
        LabelListCreateView.as_view(),
        name="label-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/labels/<uuid:pk>/",
        LabelDetailView.as_view(),
        name="label-detail",
    ),
    # 이슈 일괄 업데이트
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/bulk/",
        IssueBulkUpdateView.as_view(),
        name="issue-bulk-update",
    ),
    # 이슈 일괄 삭제
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/bulk-delete/",
        IssueBulkDeleteView.as_view(),
        name="issue-bulk-delete",
    ),
    # 이슈 템플릿
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/templates/",
        IssueTemplateListCreateView.as_view(),
        name="issue-template-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/templates/<uuid:pk>/",
        IssueTemplateDetailView.as_view(),
        name="issue-template-detail",
    ),
    # 내 할 일 — 워크스페이스 홈용
    path(
        "workspaces/<slug:workspace_slug>/issues/my/",
        WorkspaceMyIssuesView.as_view(),
        name="workspace-my-issues",
    ),
    # 이슈 통계 — 프로젝트 대시보드 차트용
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/stats/",
        ProjectIssueStatsView.as_view(),
        name="project-issue-stats",
    ),
    path(
        "workspaces/<slug:workspace_slug>/issues/recent/",
        WorkspaceRecentIssuesView.as_view(),
        name="workspace-recent-issues",
    ),
    path(
        "workspaces/<slug:workspace_slug>/issues/search/",
        WorkspaceIssueSearchView.as_view(),
        name="workspace-issue-search",
    ),
    # 이슈에 연결된 문서
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/issues/<uuid:pk>/documents/",
        IssueDocumentLinksView.as_view(),
        name="issue-document-links",
    ),

    # 요청 큐 (버그/기능 제출 → 승인/거절)
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/requests/",
        IssueRequestListCreateView.as_view(),
        name="issue-request-list",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/requests/<uuid:pk>/approve/",
        IssueRequestApproveView.as_view(),
        name="issue-request-approve",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/requests/<uuid:pk>/reject/",
        IssueRequestRejectView.as_view(),
        name="issue-request-reject",
    ),
    path(
        "workspaces/<slug:workspace_slug>/projects/<uuid:project_pk>/requests/<uuid:pk>/",
        IssueRequestDeleteView.as_view(),
        name="issue-request-delete",
    ),
]
